# Change these first
owner: batteryincludedai # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Browse
    url: https://api.batteryincluded.io/api/v1/collections/demo/documents/browse?q=phone&v[locale]=de
    headers:
      - "X-BI-API-KEY: demo-key"
  - name: Suggest
    url: https://api.batteryincluded.io/api/v1/collections/demo/documents/suggest?q=phone&v[locale]=de
    headers:
      - "X-BI-API-KEY: demo-key"
status-website:
  themeUrl: https://status.batteryincluded.io/theme.css
  cname: status.batteryincluded.io
  logoUrl: https://batteryincluded.ai/wp-content/uploads/2023/12/BI-Logo-Header-1@300x-8-1.png
  #favicon: https://example.com/favicon.png
  #skipDescriptionUpdate: true
  faviconSvg: https://portal.batteryincluded.io/icon.svg
  name: BatteryIncluded
  introTitle: "API Status"
  introMessage: ""
  navbar:
    #- title: Status
    #  href: /
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# default setting
workflowSchedule:
  #graphs: "0 0 * * *"
  responseTime: "*/5 * * * *"
  #staticSite: "0 1 * * *"
  #summary: "0 0 * * *"
  #updateTemplate: "0 0 * * *"
  #updates: "0 3 * * *"
  uptime: "*/5 * * * *"

runner: "[self-hosted, linux, X64]"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
