# Change these first
owner: batteryincludedai # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Browse
    url: https://api.batteryincluded.io/api/v1/collections/demo/documents/browse?q=phone
    headers:
      - "X-BI-API-KEY: demo-key"
#  - name: Wikipedia
#    url: https://en.wikipedia.org
#  - name: Hacker News
#    url: https://news.ycombinator.com
#  - name: Test Broken Site
#    url: https://thissitedoesnotexist.koj.co
#  - name: IPv6 test
#    url: forwardemail.net
#    port: 80
#    check: "tcp-ping"
#    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.batteryincluded.io
  # baseUrl: /your-repo-name
  logoUrl: https://batteryincluded.ai/wp-content/uploads/2023/12/BI-Logo-Header-1@300x-8-1.png
  name: BatteryIncluded
  introTitle: "API Status"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
